# Generated by Django 2.2.10 on 2020-03-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardCvv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_no', models.CharField(max_length=6)),
                ('card_type', models.CharField(max_length=100)),
                ('card_category', models.CharField(max_length=100)),
                ('refund', models.CharField(max_length=10)),
                ('card_mark', models.CharField(max_length=20)),
                ('expiry', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_no', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('base', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CardDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_no', models.CharField(max_length=6)),
                ('track', models.CharField(max_length=20)),
                ('carr', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=50)),
                ('card_category', models.CharField(max_length=50)),
                ('refund', models.CharField(max_length=10)),
                ('card_mark', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('dumped_in', models.CharField(max_length=50)),
                ('base', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CardMarket',
            fields=[
                ('name', models.CharField(max_length=20, unique=True)),
                ('url', models.URLField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('require_credetials', models.BooleanField(default=True)),
                ('require_captcha', models.BooleanField(default=True)),
                ('market_identity', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Test Checkpoint', max_length=20, unique=True)),
                ('next_index', models.PositiveIntegerField(default=0)),
                ('Checkpoint_identity', models.IntegerField(choices=[(11, 'Brocard Dumps'), (12, 'Brocard CVVs'), (21, 'MeccaDumps Dumps'), (22, 'MeccaDumps CVVs'), (31, 'Franklins Dumps'), (32, 'Franklins CVVs'), (1001, 'Indexed Forums'), (1002, 'Emails & Pass')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=50, unique=True)),
                ('alpha3_code', models.CharField(default='Test', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Crawler_Breaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(default='Descriptive Name', max_length=50)),
                ('breaker', models.BooleanField(default=False)),
                ('identifier', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlerAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Descriptive Name', max_length=50)),
                ('Access_identity', models.IntegerField(choices=[(100, 'Dump Cvv Collectors'), (200, 'Indexed Forums'), (300, 'Emails & Pass'), (400, 'Authorization to Control Dynamic Crawler')], unique=True)),
                ('authorize_access', models.BooleanField(default=False)),
                ('authorize_cancel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email_passwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=40)),
                ('source', models.CharField(default='unknown', max_length=150)),
                ('domain', models.CharField(max_length=50)),
                ('before_at', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150)),
                ('hash', models.CharField(max_length=255)),
                ('ipaddress', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='source', max_length=50)),
                ('path', models.CharField(default='Give a path', max_length=255)),
                ('status', models.CharField(default='never started', max_length=255)),
                ('break_point', models.CharField(default=':', max_length=50)),
                ('identifier', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='email_passwords',
            constraint=models.UniqueConstraint(fields=('email', 'password', 'source'), name='email password source unique'),
        ),
    ]
