# Generated by Django 2.2.10 on 2020-03-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherdumps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_passwords',
            name='domain',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='email',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='hash',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='ipaddress',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='password',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='phonenumber',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='username',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
