# Generated by Django 2.2.10 on 2020-03-25 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatherdumps', '0002_auto_20200325_0402'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='email_passwords',
            index_together={('domain', 'before_at')},
        ),
    ]
