# Generated by Django 2.2.10 on 2020-03-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherdumps', '0003_auto_20200325_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_passwords',
            name='before_at',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='domain',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='email',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='hash',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='ipaddress',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='password',
            field=models.CharField(db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='phonenumber',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='source',
            field=models.CharField(default='unknown', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='username',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
    ]
