# Generated by Django 2.2.10 on 2020-04-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherdumps', '0004_auto_20200325_1018'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='email_passwords',
            name='email password source unique',
        ),
        migrations.AddConstraint(
            model_name='email_passwords',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), ('username__isnull', True)), fields=('email', 'password', 'source'), name='email password source unique'),
        ),
        migrations.AddConstraint(
            model_name='email_passwords',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', True), ('username__isnull', False)), fields=('username', 'password', 'source'), name='username password source unique'),
        ),
        migrations.AddConstraint(
            model_name='email_passwords',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), ('username__isnull', False)), fields=('username', 'email', 'password', 'source'), name='username  email password source unique'),
        ),
    ]
