# Generated by Django 2.2.10 on 2020-04-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherdumps', '0005_auto_20200412_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcvv',
            name='bank',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cardcvv',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cardcvv',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carddump',
            name='bank',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carddump',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
