# Generated by Django 2.2.10 on 2020-04-15 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherdumps', '0006_auto_20200415_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcvv',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='carddump',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
