# Generated by Django 2.2.10 on 2020-05-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherdumps', '0008_auto_20200528_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_passwords',
            name='before_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='domain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='ipaddress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='email_passwords',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
