# Generated by Django 2.2.10 on 2020-05-16 20:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FolderSelectInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(max_length=10000)),
                ('extensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, size=None)),
                ('parser', models.CharField(max_length=100)),
                ('start_line', models.PositiveIntegerField(default=0)),
                ('additional_file_path', models.CharField(blank=True, max_length=10000)),
                ('regex_for_additional_file_path', models.CharField(blank=True, max_length=255)),
                ('additional_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FileReadInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveIntegerField(max_length=10)),
                ('order', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('delimeter', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[':'], size=None)),
                ('file_name', models.CharField(blank=True, max_length=150)),
                ('file_name_regex', models.NullBooleanField(default=False)),
                ('start_line', models.PositiveIntegerField(blank=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileparser.FolderSelectInfoModel')),
            ],
        ),
    ]
