# Generated by Django 2.2.10 on 2020-05-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderselectinfomodel',
            name='folder_path',
            field=models.CharField(max_length=10000, unique=True),
        ),
    ]
