# Generated by Django 2.2.10 on 2020-05-16 20:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileparser', '0002_auto_20200516_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filereadinfomodel',
            name='delimeter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='filereadinfomodel',
            name='length',
            field=models.PositiveIntegerField(),
        ),
    ]
