# Generated by Django 2.2.10 on 2020-05-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileparser', '0003_auto_20200516_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filereadinfomodel',
            name='start_line',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
