# Generated by Django 2.2.10 on 2020-03-25 01:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='', max_length=255)),
                ('username', models.CharField(default='', max_length=255)),
                ('useremail', models.CharField(default='', max_length=255)),
                ('type', models.CharField(default='', max_length=255)),
                ('search_term', models.CharField(default='', max_length=1000)),
                ('search_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=200)),
                ('channel_url', models.CharField(max_length=10000)),
                ('channel_index_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_name', models.CharField(max_length=255)),
                ('chart_file', models.CharField(max_length=255)),
                ('chart_user', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghostfrpasswords', jsonfield.fields.JSONField(blank=True)),
                ('breaches', jsonfield.fields.JSONField(blank=True)),
                ('no_of_paste', models.PositiveIntegerField(blank=True)),
                ('indexemails', jsonfield.fields.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomainEmailStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('passwords', jsonfield.fields.JSONField(blank=True)),
                ('darknet_occurrences', jsonfield.fields.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailmonitoring', models.BooleanField(default=False)),
                ('domainmonitoring', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IndexEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('channel_name', models.CharField(max_length=200)),
                ('channel_url', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_message', models.TextField()),
                ('msg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='', max_length=50, unique=True)),
                ('support_email', models.EmailField(default='daudahmed@zoho.com', max_length=254)),
                ('userid', models.CharField(default='', max_length=255)),
                ('allow_monitoring', models.BooleanField(default=True)),
                ('asset_type', models.CharField(default='Domain', max_length=50)),
                ('asset_status', models.CharField(default='In Active', max_length=50)),
                ('asset_verify', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=50)),
                ('userid', models.CharField(default='', max_length=255)),
                ('fileid', models.CharField(default='', max_length=255)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileid', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=50)),
                ('report_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('request_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('create_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('search_term', models.CharField(max_length=1000)),
                ('search_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='monitoremail',
            constraint=models.UniqueConstraint(fields=('fileid', 'userid', 'email'), name='uniqueness constraints'),
        ),
        migrations.AddField(
            model_name='domainemailstatus',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.MonitorDomain'),
        ),
        migrations.AddField(
            model_name='currentstatus',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em', to='search.MonitorEmail'),
        ),
    ]
