# Generated by Django 2.2.10 on 2020-03-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
