# Generated by Django 2.2.10 on 2020-03-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200325_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
