# Generated by Django 2.2.10 on 2020-07-01 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20200325_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(default='', max_length=50)),
                ('support_email', models.EmailField(default='daudahmed@zoho.com', max_length=254)),
                ('userid', models.CharField(default='', max_length=255)),
                ('fileid', models.CharField(default='', max_length=255)),
                ('allow_monitoring', models.BooleanField(default=True)),
                ('asset_type', models.CharField(default='Domain', max_length=50)),
                ('asset_status', models.CharField(default='In Active', max_length=50)),
                ('asset_verify', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='domainemailstatus',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.MonitorAsset'),
        ),
        migrations.DeleteModel(
            name='MonitorDomain',
        ),
    ]
