# Generated by Django 2.2.10 on 2020-07-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20200701_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalvar',
            old_name='domainmonitoring',
            new_name='monitoring',
        ),
        migrations.RemoveField(
            model_name='globalvar',
            name='emailmonitoring',
        ),
        migrations.AddField(
            model_name='globalvar',
            name='type',
            field=models.CharField(default='email', max_length=50, unique=True),
        ),
    ]
