# Generated by Django 2.2.10 on 2020-07-01 12:23

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_monitorasset_allow_external'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAssetStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', jsonfield.fields.JSONField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_name', to='search.MonitorAsset')),
            ],
        ),
    ]
