# Generated by Django 2.2.10 on 2020-07-01 19:28

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20200701_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentassetstatus',
            name='records',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
    ]
