# Generated by Django 2.2.10 on 2020-07-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20200701_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentstatus',
            name='email',
        ),
        migrations.RemoveField(
            model_name='domainemailstatus',
            name='domain',
        ),
        migrations.AddConstraint(
            model_name='monitorasset',
            constraint=models.UniqueConstraint(condition=models.Q(asset_type='email'), fields=('fileid', 'userid', 'asset'), name='uniqueness constraint email asset'),
        ),
        migrations.AddConstraint(
            model_name='monitorasset',
            constraint=models.UniqueConstraint(condition=models.Q(asset_type='domain'), fields=('userid', 'asset'), name='uniqueness constraint domain asset'),
        ),
        migrations.DeleteModel(
            name='CurrentStatus',
        ),
        migrations.DeleteModel(
            name='DomainEmailStatus',
        ),
    ]
