# Generated by Django 2.2.10 on 2020-07-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20200702_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorasset',
            name='fileid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
