# Generated by Django 2.2.10 on 2020-07-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20200702_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonitorEmail',
        ),
    ]
